# Generated by Django 3.1.5 on 2021-01-12 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210111_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
