# Generated by Django 3.1.5 on 2021-01-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
